In [416]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [417]:
df = pd.read_csv(r"D:\Study\BA\Accidental Drug Related Deaths\data.csv")

# Checking DataSet

In [418]:
df.head()

Case_Number        Date  Gender          Race   Age        City  \
0     14-0273  2014-06-28     NaN           NaN   NaN         NaN   
1     13-0102  2013-03-21    Male         Black  48.0     NORWALK   
2     16-0165  2016-03-13  Female         White  30.0  SANDY HOOK   
3     16-0208  2016-03-31    Male         White  23.0         RYE   
4     13-0052  2013-02-13    Male  Asian, Other  22.0    FLUSHING   

  State_Abbreviation       County Death_City Death_County  ... Is_Amphetamine  \
0                NaN          NaN        NaN          NaN  ...            NaN   
1                NaN          NaN    NORWALK    FAIRFIELD  ...            NaN   
2                 CT    FAIRFIELD    DANBURY          NaN  ...            NaN   
3                 NY  WESTCHESTER  GREENWICH          NaN  ...            NaN   
4                NaN       QUEENS  GREENWICH    FAIRFIELD  ...            NaN   

  Is_Tramadol Is_Morphine Is_Hydromorphone Other Is_OpiateNOS Is_Any_Opioid  \
0         NaN         NaN              NaN   NaN          NaN           NaN   
1         NaN         NaN              NaN   NaN          NaN           NaN   
2         NaN         NaN              NaN   NaN          NaN          True   
3         NaN         NaN              NaN   NaN          NaN          True   
4         NaN         NaN              NaN   NaN          NaN           NaN   

  Manner_of_Death   Latitude  Longitude  
0        Accident  41.575155 -72.738288  
1        Accident        NaN        NaN  
2        Accident  41.393666 -73.451539  
3        Accident  41.026526 -73.628549  
4        Accident  41.026526 -73.628549  

[5 rows x 33 columns]

# Dropping variable that wont be included

In [419]:
df = df.drop(["Case_Number","Date","City","State_Abbreviation","County","Death_City","Death_County","Immediate_Cause","Description_of_Injury","Latitude","Longitude","Injury_Place","Other","Is_Any_Opioid"],axis=1)

In [420]:
df.head()

Gender          Race   Age  Location Is_Heroin Is_Cocaine Is_Fentanyl  \
0     NaN           NaN   NaN       NaN       NaN        NaN        true   
1    Male         Black  48.0  Hospital       NaN       True         NaN   
2  Female         White  30.0  Hospital      True       True         NaN   
3    Male         White  23.0  Hospital      True        NaN        true   
4    Male  Asian, Other  22.0  Hospital       NaN        NaN        true   

  Is_Oxycodone Is_Oxymorphone Is_EtOH Is_Hydrocodone Is_Benzodiazepine  \
0          NaN            NaN     NaN            NaN              True   
1          NaN            NaN     NaN            NaN               NaN   
2          NaN            NaN     NaN            NaN               NaN   
3          NaN            NaN     NaN            NaN               NaN   
4          NaN            NaN     NaN            NaN               NaN   

  Is_Methadone Is_Amphetamine Is_Tramadol Is_Morphine Is_Hydromorphone  \
0         True            NaN         NaN         NaN              NaN   
1          NaN            NaN         NaN         NaN              NaN   
2          NaN            NaN         NaN         NaN              NaN   
3          NaN            NaN         NaN         NaN              NaN   
4          NaN            NaN         NaN         NaN              NaN   

  Is_OpiateNOS Manner_of_Death  
0          NaN        Accident  
1          NaN        Accident  
2          NaN        Accident  
3          NaN        Accident  
4          NaN        Accident

In [421]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5104 entries, 0 to 5103
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             5098 non-null   object 
 1   Race               5091 non-null   object 
 2   Age                5101 non-null   float64
 3   Location           5080 non-null   object 
 4   Is_Heroin          2529 non-null   object 
 5   Is_Cocaine         1521 non-null   object 
 6   Is_Fentanyl        2231 non-null   object 
 7   Is_Oxycodone       389 non-null    object 
 8   Is_Oxymorphone     607 non-null    object 
 9   Is_EtOH            108 non-null    object 
 10  Is_Hydrocodone     1247 non-null   object 
 11  Is_Benzodiazepine  118 non-null    object 
 12  Is_Methadone       1342 non-null   object 
 13  Is_Amphetamine     474 non-null    object 
 14  Is_Tramadol        159 non-null    object 
 15  Is_Morphine        130 non-null    object 
 16  Is_Hydromorphone   41 no

In [422]:
df.describe()

Age
count  5101.000000
mean     41.967653
std      12.336298
min      14.000000
25%      32.000000
50%      42.000000
75%      52.000000
max      87.000000

# Unique in Target Variable

In [423]:
df["Manner_of_Death"].unique()

array(['Accident', 'accident', nan, 'Pending', 'ACCIDENT', 'Natural'],
      dtype=object)

In [424]:
df["Manner_of_Death"] = np.where(df["Manner_of_Death"]=="accident","Accident",df["Manner_of_Death"])
df["Manner_of_Death"] = np.where(df["Manner_of_Death"]=="ACCIDENT","Accident",df["Manner_of_Death"])

In [425]:
df["Manner_of_Death"].unique()

array(['Accident', nan, 'Pending', 'Natural'], dtype=object)

### Dropping Which are null or Pending

In [426]:
df = df.loc[~(df["Manner_of_Death"].isnull()|(df["Manner_of_Death"]=="Pending"))]

In [427]:
df["Manner_of_Death"].unique()

array(['Accident', 'Natural'], dtype=object)

# Seprating Object and Numeric data

In [428]:
Text = df.select_dtypes(include="object").info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5080 entries, 0 to 5103
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Gender             5075 non-null   object
 1   Race               5068 non-null   object
 2   Location           5059 non-null   object
 3   Is_Heroin          2522 non-null   object
 4   Is_Cocaine         1514 non-null   object
 5   Is_Fentanyl        2228 non-null   object
 6   Is_Oxycodone       389 non-null    object
 7   Is_Oxymorphone     603 non-null    object
 8   Is_EtOH            108 non-null    object
 9   Is_Hydrocodone     1242 non-null   object
 10  Is_Benzodiazepine  116 non-null    object
 11  Is_Methadone       1337 non-null   object
 12  Is_Amphetamine     473 non-null    object
 13  Is_Tramadol        159 non-null    object
 14  Is_Morphine        130 non-null    object
 15  Is_Hydromorphone   41 non-null     object
 16  Is_OpiateNOS       85 non-null     object


In [429]:
Num = df.select_dtypes(exclude="object").info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5080 entries, 0 to 5103
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Age     5078 non-null   float64
dtypes: float64(1)
memory usage: 79.4 KB


# Checking Unique Value

In [430]:
df.nunique()

Gender                3
Race                 11
Age                  65
Location              6
Is_Heroin             1
Is_Cocaine            1
Is_Fentanyl           4
Is_Oxycodone          1
Is_Oxymorphone        1
Is_EtOH               1
Is_Hydrocodone        1
Is_Benzodiazepine     1
Is_Methadone          1
Is_Amphetamine        1
Is_Tramadol           1
Is_Morphine           1
Is_Hydromorphone      4
Is_OpiateNOS          1
Manner_of_Death       2
dtype: int64

In [431]:
df["Gender"].unique()

array([nan, 'Male', 'Female', 'Unknown'], dtype=object)

In [432]:
df = df.loc[~(df["Gender"].isnull()|(df["Gender"]=="Unknown"))]

In [433]:
df["Race"].unique()

array(['Black', 'White', 'Asian, Other', 'Hispanic, White', nan,
       'Asian Indian', 'Hispanic, Black', 'Unknown', 'Other', 'Chinese',
       'Native American, Other', 'Hawaiian'], dtype=object)

In [434]:
df["Race"] = df["Race"].fillna(df["Race"].mode()[0])

In [435]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [436]:
df["Location"].unique()

array(['Hospital', 'Residence', 'Other', 'Nursing Home', nan,
       'Convalescent Home', 'Hospice'], dtype=object)

In [437]:
df["Location"] = df["Location"].fillna(df["Location"].mode()[0])

In [438]:
df["Is_Heroin"] = np.where(df["Is_Heroin"]=="True",1,0)

In [439]:
df["Is_Cocaine"] = np.where(df["Is_Cocaine"]=="True",1,0)

In [440]:
df["Is_Fentanyl"].unique()

array([nan, 'true', 'true-a', 'true pops', 'true (ptch)'], dtype=object)

In [441]:
df["Is_Fentanyl"] = np.where(df["Is_Fentanyl"]=="true",1,df["Is_Fentanyl"])
df["Is_Fentanyl"] = np.where(df["Is_Fentanyl"]=="true-a",1,df["Is_Fentanyl"])
df["Is_Fentanyl"] = np.where(df["Is_Fentanyl"]=="true pops",1,df["Is_Fentanyl"])
df["Is_Fentanyl"] = np.where(df["Is_Fentanyl"]=="true (ptch)",1,df["Is_Fentanyl"])
df["Is_Fentanyl"] = np.where(df["Is_Fentanyl"]==1,1,0)

In [442]:
df["Is_Oxycodone"] = np.where(df["Is_Oxycodone"]=="True",1,0)

In [443]:
df["Is_Oxymorphone"] = np.where(df["Is_Oxymorphone"]=="True",1,0)

In [444]:
df["Is_EtOH"] = np.where(df["Is_EtOH"]=="True",1,0)

In [445]:
df["Is_Hydrocodone"] = np.where(df["Is_Hydrocodone"]=="True",1,0)

In [446]:
df["Is_Benzodiazepine"] = np.where(df["Is_Benzodiazepine"]=="True",1,0)

In [447]:
df["Is_Methadone"] = np.where(df["Is_Methadone"]=="True",1,0)

In [448]:
df["Is_Amphetamine"] = np.where(df["Is_Amphetamine"]=="True",1,0)

In [449]:
df["Is_Tramadol"] = np.where(df["Is_Tramadol"]=="True",1,0)

In [450]:
df["Is_Morphine"] = np.where(df["Is_Morphine"]=="True",1,0)

In [451]:
df["Is_Hydromorphone"].unique()

array([nan, 'true', 'truees', 'falseo rx but straws', 'pcp falseeg'],
      dtype=object)

In [452]:
df["Is_Hydromorphone"] = np.where(df["Is_Hydromorphone"]=="true",1,df["Is_Hydromorphone"])
df["Is_Hydromorphone"] = np.where(df["Is_Hydromorphone"]=="truees",1,df["Is_Hydromorphone"])
df["Is_Hydromorphone"] = np.where(df["Is_Hydromorphone"]=="falseo rx but straws",2,df["Is_Hydromorphone"])
df["Is_Hydromorphone"] = np.where(df["Is_Hydromorphone"]=="pcp falseeg",3,df["Is_Hydromorphone"])

In [453]:
df["Is_Hydromorphone"] = df["Is_Hydromorphone"].fillna(0)

In [454]:
df["Is_OpiateNOS"] = np.where(df["Is_OpiateNOS"]=="True",1,0)

# Missing Value

In [455]:
df.isna().sum()

Gender               0
Race                 0
Age                  0
Location             0
Is_Heroin            0
Is_Cocaine           0
Is_Fentanyl          0
Is_Oxycodone         0
Is_Oxymorphone       0
Is_EtOH              0
Is_Hydrocodone       0
Is_Benzodiazepine    0
Is_Methadone         0
Is_Amphetamine       0
Is_Tramadol          0
Is_Morphine          0
Is_Hydromorphone     0
Is_OpiateNOS         0
Manner_of_Death      0
dtype: int64

In [456]:
df.nunique()

Gender                2
Race                 11
Age                  65
Location              6
Is_Heroin             1
Is_Cocaine            1
Is_Fentanyl           2
Is_Oxycodone          1
Is_Oxymorphone        1
Is_EtOH               1
Is_Hydrocodone        1
Is_Benzodiazepine     1
Is_Methadone          1
Is_Amphetamine        1
Is_Tramadol           1
Is_Morphine           1
Is_Hydromorphone      4
Is_OpiateNOS          1
Manner_of_Death       2
dtype: int64

In [457]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5074 entries, 1 to 5103
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             5074 non-null   object 
 1   Race               5074 non-null   object 
 2   Age                5074 non-null   float64
 3   Location           5074 non-null   object 
 4   Is_Heroin          5074 non-null   int32  
 5   Is_Cocaine         5074 non-null   int32  
 6   Is_Fentanyl        5074 non-null   int32  
 7   Is_Oxycodone       5074 non-null   int32  
 8   Is_Oxymorphone     5074 non-null   int32  
 9   Is_EtOH            5074 non-null   int32  
 10  Is_Hydrocodone     5074 non-null   int32  
 11  Is_Benzodiazepine  5074 non-null   int32  
 12  Is_Methadone       5074 non-null   int32  
 13  Is_Amphetamine     5074 non-null   int32  
 14  Is_Tramadol        5074 non-null   int32  
 15  Is_Morphine        5074 non-null   int32  
 16  Is_Hydromorphone   5074 

In [458]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Gender"] = le.fit_transform(df["Gender"])
df["Race"] = le.fit_transform(df["Race"])
df["Location"] = le.fit_transform(df["Location"])
df["Manner_of_Death"] = le.fit_transform(df["Manner_of_Death"])

In [459]:
df["Manner_of_Death"].unique()

array([0, 1])

In [521]:
x = df.drop(columns=["Manner_of_Death"])
y = df["Manner_of_Death"]

In [522]:
y.shape,x.shape

((5074,), (5074, 18))

In [523]:
from sklearn.model_selection import train_test_split

In [531]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=10)

In [532]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((3551, 18), (1523, 18), (3551,), (1523,))

In [533]:
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [534]:
XGB = XGBClassifier(n_estimators=100,learning_rate=0.01,max_depth=5,min_child_weight=10,use_label_encoder=False)

In [535]:
Mat = [(x_test,y_test)]
XGB.fit(x_train,y_train,eval_metric=["logloss","error"],eval_set=Mat,verbose=0)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.01, max_delta_step=0,
              max_depth=5, min_child_weight=10, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=8,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', use_label_encoder=False,
              validate_parameters=1, verbosity=None)

In [536]:
predictXGB = XGB.predict(x_test)

In [537]:
confusion_matrix(predictXGB,y_test)

array([[1523]], dtype=int64)

In [544]:
import statsmodels.api as sm
lm = sm.OLS(y_train,x_train).fit()
lm.summary()

D:\Program\lib\site-packages\statsmodels\regression\linear_model.py:1860: RuntimeWarning: divide by zero encountered in double_scalars
  return np.sqrt(eigvals[0]/eigvals[-1])


<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:        Manner_of_Death   R-squared (uncentered):                   0.001
Model:                            OLS   Adj. R-squared (uncentered):             -0.001
Method:                 Least Squares   F-statistic:                             0.5781
Date:                Wed, 26 Jan 2022   Prob (F-statistic):                       0.748
Time:                        02:44:09   Log-Likelihood:                          9477.8
No. Observations:                3551   AIC:                                 -1.894e+04
Df Residuals:                    3545   BIC:                                 -1.891e+04
Df Model:                           6                                                  
Covariance Type:            nonrobust                                                  
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Gender                0.0002      0.001      0.330      0.741      -0.001       0.001
Race                -3.3e-05   9.05e-05     -0.365      0.715      -0.000       0.000
Age                1.564e-05   1.84e-05      0.851      0.395   -2.04e-05    5.17e-05
Location           2.663e-05      0.000      0.135      0.893      -0.000       0.000
Is_Heroin          1.539e-18   6.34e-18      0.243      0.808   -1.09e-17     1.4e-17
Is_Cocaine                 0          0        nan        nan           0           0
Is_Fentanyl          -0.0006      0.001     -1.064      0.287      -0.002       0.001
Is_Oxycodone               0          0        nan        nan           0           0
Is_Oxymorphone             0          0        nan        nan           0           0
Is_EtOH                    0          0        nan        nan           0           0
Is_Hydrocodone             0          0        nan        nan           0           0
Is_Benzodiazepine          0          0        nan        nan           0           0
Is_Methadone               0          0        nan        nan           0           0
Is_Amphetamine             0          0        nan        nan           0           0
Is_Tramadol                0          0        nan        nan           0           0
Is_Morphine                0          0        nan        nan           0           0
Is_Hydromorphone     -0.0006      0.003     -0.225      0.822      -0.006       0.005
Is_OpiateNOS               0          0        nan        nan           0           0
==============================================================================
Omnibus:                    11968.141   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):       1858462046.095
Skew:                          59.516   Prob(JB):                         0.00
Kurtosis:                    3545.110   Cond. No.                          inf
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The smallest eigenvalue is      0. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [546]:
final = lm.predict(x_test)
prediction = list(map(round,final))

In [547]:
cm = confusion_matrix(y_test, prediction)

In [548]:
cm

array([[1523]], dtype=int64)

In [549]:
from sklearn.metrics import accuracy_score

In [550]:
accuracy = accuracy_score(y_test, prediction)
accuracy

1.0